apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: rhbk
  namespace: rhbk
spec:
  users:
    - name: rhbk
      databases:
        - keycloak
      options: 'SUPERUSER'
  backups:
    pgbackrest:
      global:
        repo2-retention-full: "1"
        repo2-retention-full-type: count
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
          schedules:
            full: "*/10 * * * *"
            differential: "2-59/5 * * * *"
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: instance1
      replicas: 1
  postgresVersion: 17
