cluster:
  instances: 1
  primary:
    user: rhbk
    database: keycloak
  storage:
    size: "10Gi"
  import:
    source:
      host: rhbk-primary.rhbk.svc
      user: rhbk
      dbname: keycloak
      password:
        name: rhbk-pguser-rhbk
        key: password
