fullnameOverride: cpg
cluster:
  instance: 1
  primary:
    user: rhbk
    database: keycloak
  import:
    source:
      host: rhbk-primary.rhbk.svc
      user: rhbk
      dbname: keycloak
      password:
        name: rhbk-pguser-rhbk
        key: password
