{{- if .Values.pooler.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: {{ include "stakater-cloudnative-pg.fullname" . }}-pooler
  labels:
    {{- include "stakater-cloudnative-pg.labels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "stakater-cloudnative-pg.fullname" . }}-cluster
  instances: {{ .Values.pooler.instances }}
  type: rw
  serviceTemplate:
    metadata:
      labels:
        {{- include "stakater-cloudnative-pg.labels" . | nindent 4 }}-pooler
    spec:
      type: LoadBalancer
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "{{ .Values.pooler.connections.max }}"
      default_pool_size: "{{ .Values.pooler.size }}"
{{- end }}
